samel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('medico', 'MedicoController');
Route::resource('paciente', 'PacienteController');
Route::resource('atendimento', 'AtendimentoController');
Route::resource('relatorio', 'RelatorioController');

//pesquisas na tela de atendimento
Route::post('atendimento/search/medico', 'MedicoController@search')->name('search.medico');
Route::post('atendimento/search/paciente', 'PacienteController@search')->name('search.paciente');

Route::post('atendimento/{id}/search/medico', 'MedicoController@search')->name('search.medico');
Route::post('atendimento/{id}/search/paciente', 'PacienteController@search')->name('search.paciente');

//pesquisa do relatorio
Route::post('relatorio/search/periodo', 'RelatorioController@search')->name('search.relatorio');

samel/app/Medico.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Medico extends Model
{
    protected $table = 'medicos';

    protected $fillable = [
        'nome', 'especialidade','crm'
    ];
}

samel/app/Http/Controllers/Api/MedicoController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;


class MedicoController extends Controller
{
     //INTEGRAÇÃO API 
     public function getCRM(Request $request){
        try {
            $data = json_decode($request->getContent());
            if($data->crm != ""){
                
                //procura dados do medico
                $dadosmedico = DB::table('medicos')->where('medicos.crm', '=', $data->crm)->get();
                
                if(!$dadosmedico || count($dadosmedico) == 0 || empty($dadosmedico) || $dadosmedico == []){               
                    return response()->json(['erro'=>'Médico não foi encontrado'], 404); 
                }
                $medico = $dadosmedico[0];

                //procura atendimento do medico encontrado
                $atendimentos = DB::table('atendimentos') 
                ->join('pacientes', 'pacientes.id', '=', 'atendimentos.paciente_id')
                ->whereNull('atendimentos.deleted_at')
                ->where('atendimentos.medico_id', '=', $medico->id)
                ->select('atendimentos.id', 'atendimentos.dia', 
                          'pacientes.nome as paciente', 'pacientes.telefone', 'pacientes.plano')
                ->orderBy('atendimentos.id', 'DESC')->get(); 

                $json = ['medico'=>$medico, 'atendimentos'=> $atendimentos];
                
                return response()->json($json);
            }else{
                return response()->json('CRM inválido', 404);
            }           

        } catch (\Exception $e) {
            if(config('app.debug')){
                return response()->json($e->getMessage(), 404);
            }
            return response()->json('Existe um erro na operação', 404);
        }           
    }
}

samel/app/Http/Controllers/MedicoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Medico;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class MedicoController extends Controller
{
   
    
        private $medico;
    
        public function __construct(Medico $medico){

            $this->medico = $medico;
            $this->middleware('auth');
        }
        //view que mostra medico por id
        public function show($id){
            try {
                $data = DB::table('medicos') 
                                ->where([['medicos.id', '=', $id]])
                                ->get();         
                if(!$data || count($data) == 0 || empty($data) || $data == []){               
                    return redirect('medico/')->with('error', 'Médico não encontrado');  
                }
                $medico = $data[0];
                
                return view('medico.view', compact('medico'));
            } catch (\Exception $e) {
                if(config('app.debug')){
                    return redirect('medico/')->with('error', $e->getMessage()); 
                }
                return redirect('medico/')->with('error', 'Existe um erro na operação'); 
            }
    
            
        }
        //view de edicao
        public function edit($id){
    
            try {
                $medico = $this->medico->findOrFail($id);          
                return view('medico.edit', compact('medico'));
    
            } catch (\Exception $e) {
                if(config('app.debug')){
                    return redirect('medico/')->with('error', $e->getMessage()); 
                }
                return redirect('medico/')->with('error', 'Existe um erro na operação'); 
            }        
        }
        //exclui registro
        public function destroy($id){
    
            try {
                $medico = $this->medico->findOrFail($id); 
                $medico->delete(); 
                
                return redirect('medico/')->with('success', 'Médico excluído com sucesso'); 
    
            } catch (\Exception $e) {
                if(config('app.debug')){
                    return redirect('medico/')->with('error', $e->getMessage()); 
                }
                return redirect('medico/')->with('error', 'Existe um erro na operação'); 
            }   
        }
        //view de listagem de todos
        public function index(){
          
                $medicos = $this->medico->whereNull('deleted_at')
                                    ->orderBy('id', 'DESC')->paginate(30);
                return view('medico.index', compact('medicos'));
                   
        }
        //view de cadastro
        public function create(){
            return view('medico.create');
        }
        //cadastra
        public function store(Request $request){
    
                //usa isso para validar os campos com os valores inseridos
                $this->validate($request, ['nome'=>'required|string|max:300|regex:/^[a-zA-Z\s]*$/', 
                                            'especialidade'=>'required|string|max:255',
                                            'crm' => 'required |string | max:30']);
                try {
                $data = $request->all();    
                $medico = $this->medico->create($data);
    
                return redirect('medico/')->with('success', 'Médico criado com sucesso'); 
                
            } catch (\Exception $e) {
                if(config('app.debug')){
                    return redirect('medico/')->with('error', $e->getMessage()); 
                }
                return redirect('medico/')->with('error', 'Existe um erro na operação'); 
            }         
        }
        //edita 
        public function update(Request $request, $id){        
           
            $this->validate($request, ['nome'=>'required|string|max:300|regex:/^[a-zA-Z\s]*$/', 
                                           'especialidade'=>'required|string|max:255',
                                           'crm' => 'required |string | max:30']);
            try {
                $data = $request->all();  
                $medico = $this->medico->findOrFail($id);
                $medico->update($data);
    
                return redirect('medico/'.$id.'/edit')->with('success', 'Médico editado com sucesso');                     
    
            } catch (\Exception $e) {
                if(config('app.debug')){
                    return redirect('medico/'.$id.'/edit')->with('error', $e->getMessage()); 
                }
                return redirect('medico/'.$id.'/edit')->with('error', 'Existe um erro na operação'); 
            }          
        }
        
        //desativa o registro apenas usando o campo deleted_at, nao exclui do banco 
        //(verificar se existe esse campo no banco)
        public function delete(Request $request, $id){
    
            $data = $request->all();
            try {      
    
                $affected = DB::table('medicos')
                  ->where('id', $id)
                  ->update(['deleted_at' => $data['deleted_at']]);
                
                return redirect('medico/')->with('success', "Médico desativado com sucesso");                      
    
            } catch (\Exception $e) {
                if(config('app.debug')){
                    return redirect('medico/')->with('error', $e->getMessage()); 
                }
                return redirect('medico/')->with('error', 'Existe um erro na operação'); 
            }          
        }

        //view de pesquisa de medico por nome
        public function search(Request $request){
            try {
                $data = json_decode($request->getContent());
                if($data->search_medico != ""){
                    $medicos = $this->medico->where('nome', 'ilike', '%'.$data->search_medico.'%')
                    ->orderBy('id', 'DESC')->paginate(30);

                    return response()->json($medicos);
                }else{
                    return response()->json([], 404);
                }           

            } catch (\Exception $e) {
                if(config('app.debug')){
                    return response()->json($e->getMessage(), 404);
                }
                return response()->json('Existe um erro na operação', 404);
            }           
        }

       
    
}

samel/resources/views/medico/create.blade.php
@extends('layouts.principal')

@section('content')
        <div class="d-sm-flex align-items-center justify-content-between ">
            <h1 class="h3 mb-0 text-gray-800">Adicionar Médico</h1>          
        </div>
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-2">
                    <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6"> 
                            <div class="p-3">
                                
                                <form class="user" method="post" action="{{ route('medico.store') }}">  
                                    @csrf
                                    <!--Nome FORM-->
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Nome:') }}</p>
                                        <input type="text" name="nome" class="form-control @error('nome') is-invalid @enderror" value="{{ old('nome') }}" id="nome" aria-describedby="nomeHelp"  autofocus placeholder="Ex: Dr. Thomas">
                                        @error('nome')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div> 
                                    <!--END Nome FORM-->

                                    <!--Especialidade FORM-->  
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Especialidade:') }}</p>
                                        <select class="form-control" name="especialidade" id="especialidade">
                                            <option value="Pediatra">Pediatra</option>
                                            <option value="Clínico Geral">Clínico Geral</option>
                                            <option value="Medicina do Trabalho">Medicina do Trabalho</option>
                                        </select>
                                    </div>
                                     <!--Especialidade FORM--> 

                                    <!--crm FORM-->                            
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('CRM:') }}</p>
                                        <input type="text" name="crm" class="form-control @error('crm') is-invalid @enderror" id="crm" aria-describedby="crmHelp" value="{{ old('crm') }}"  autocomplete="crm" autofocus placeholder="Ex: 5265">
                                        @error('crm')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                    <!--END crm FORM-->
                                   
                                    <div class="form-group row">
                                        <div class="col-md-4 mb-1 offset-md-2">
                                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                                Salvar
                                            </button>
                                        </div>    
                                        <div class="col-md-4">
                                            <a  class="btn btn-primary btn-user btn-block" style="color: #fff;" href="{{ route('medico.index') }}">
                                                Cancelar
                                            </a>
                                        </div>                         
                                    </div>  

                                </form>                                    
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

samel/resources/views/medico/edit.blade.php
@extends('layouts.principal')

@section('content')
        <div class="d-sm-flex align-items-center justify-content-between ">
            <h1 class="h3 mb-0 text-gray-800">Editar Usuário</h1>
            <!--a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a-->
        </div>
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-9">
                <a href="{{route('medico.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-1">
                    <i class="fas fa-arrow-left"></i> Voltar</a><br>
                <div class="card o-hidden border-0 shadow-lg my-2">
                    <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6"> 
                            <div class="p-3">

                                @include('utils.message')
                        
                                <form class="user" method="POST" action="{{ route('medico.update', $medico->id) }}">  
                                    @csrf
                                    @method("PUT")
                                    <!--nome FORM-->
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Nome:') }}</p>
                                        <input type="text" name="nome" class="form-control @error('nome') is-invalid @enderror" value="{{ $medico->nome }}" id="nome" aria-describedby="nomeHelp" autofocus placeholder="Ex: Dr. Thomas">
                                        @error('nome')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div> 
                                    <!--END nome FORM-->  
                                    <!--Especialidade FORM-->
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Especialidade:') }}</p>
                                        <select class="form-control" name="especialidade" id="especialidade">
                                            <option value="Pediatra" 
                                                @if ($medico->especialidade == 'Pediatra')
                                                    selected="selected"
                                                @endif >Pediatra</option>
                                            <option value="Clínico Geral"
                                                @if ($medico->especialidade == 'Clínico Geral')
                                                    selected="selected"
                                                @endif>Clínico Geral</option>
                                            <option value="Medicina do Trabalho"
                                                @if ($medico->especialidade == 'Medicina do Trabalho')
                                                    selected="selected"
                                                @endif>Medicina do Trabalho</option>
                                        </select>
                                    </div>
                                    <!--END Especialidade FORM-->
                                    <!--crm FORM-->
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('CRM:') }}</p>
                                        <input type="text" name="crm" class="form-control @error('crm') is-invalid @enderror" value="{{ $medico->crm }}" id="crm" aria-describedby="crmHelp" autofocus placeholder="Ex: 5265">
                                        @error('crm')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div> 
                                    <!--END crm FORM--> 
                                    
                                    <div class="form-group row">
                                        <div class="col-md-4 mb-1 offset-md-2">
                                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                                Salvar
                                            </button>
                                        </div>    
                                        <div class="col-md-4">
                                            <a  class="btn btn-primary btn-user btn-block" style="color: #fff;" href="{{ route('medico.index') }}">
                                                Cancelar
                                            </a>
                                        </div>                         
                                    </div>  

                                </form>                                    
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

samel/resources/views/medico/index.blade.php
@extends('layouts.principal')

@section('content')

    <a href="{{route('medico.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-1">
    <i class="fas fa-plus fa-sm text-white-50"></i> Adicionar Médico</a><br> 

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Médicos Ativos</h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                @include('utils.message')
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Especialidade</th>
                    <th>CRM</th>
                    <th>Data de Criação</th>
                    <th>Operações</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Especialidade</th>
                    <th>CRM</th>
                    <th>Data de Criação</th>
                    <th>Operações</th>
                </tr>
                </tfoot>
                <tbody> 
                @forelse($medicos as $value)
                    <tr>
                        <td>{{$value->id}}</td>
                        <td>{{$value->nome}}</td>
                        <td>{{$value->especialidade}}</td>
                        <td>{{$value->crm}}</td>
                        <td>{{$value->created_at}}</td>
                        <td>
                            
                            <a class="btn btn-info btn-sm" href="{{route('medico.show', $value->id)}}" alt="Mostrar médico" title="Mostrar médico">
                                <i class="fas fa-eye"></i></a>
                                <a class="btn btn-success btn-sm" href="{{route('medico.edit', $value->id)}}" alt="Editar médico" title="Editar médico">
                                <i class="fas fa-user-edit"></i></a>  
                                              
                                <a class="btn btn-danger btn-sm" href="#" alt="Excluir médico" title="Excluir médico" 
                                    data-toggle="modal" data-target="#inactiveModal{{$value->id}}">
                                    <i class="fas fa-lock"></i></a>                                    
                          
                                <!-- Delete Modal-->
                                <div class="modal fade" id="inactiveModal{{$value->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Deseja Excluir Médico?</h5>
                                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">Selecione "Excluir" para concluir a operação</div>
                                            <div class="modal-footer">
                                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>                                   
                                                <form action="{{ url('/medico', ['id' => $value->id]) }}" method="post">
                                                    <input class="btn btn-primary" type="submit" value="Excluir" />
                                                    @method('delete')
                                                    @csrf
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </td>
                    </tr> 
                @empty
                <tr>
                        <td colspan="6">
                            <h2>Dados Não Encontrados</h2>
                        </td>
                </tr> 

                
                @endforelse
                </tbody>
                {{$medicos->links()}}
            </table>
            </div>
        </div>
    </div>

@endsection

samel/resources/views/medico/view.blade.php
@extends('layouts.principal')

@section('content')
        <div class="d-sm-flex align-items-center justify-content-between ">
            <h1 class="h3 mb-0 text-gray-800">Visualizar Médico</h1>
            <!--a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a-->
        </div>
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-9">

            <a href="{{route('medico.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-1">
                <i class="fas fa-arrow-left"></i> Voltar</a><br>
                <div class="card o-hidden border-0 shadow-lg my-2">
                    
                    <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6"> 
                            <div class="p-3">                            
                                <p><b>Nome:</b> {{$medico->nome}}</p>
                                <p><b>Especialidade:</b> {{$medico->especialidade}}</p>
                                <p><b>CRM:</b> {{$medico->crm}}</p>
                                <p><b>Data de criação:</b> {{$medico->created_at}}</p>
                                <p><b>Última atualização:</b> {{$medico->updated_at}}</p>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>

@endsection