samel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('medico', 'MedicoController');
Route::resource('paciente', 'PacienteController');
Route::resource('atendimento', 'AtendimentoController');
Route::resource('relatorio', 'RelatorioController');

//pesquisas na tela de atendimento
Route::post('atendimento/search/medico', 'MedicoController@search')->name('search.medico');
Route::post('atendimento/search/paciente', 'PacienteController@search')->name('search.paciente');

Route::post('atendimento/{id}/search/medico', 'MedicoController@search')->name('search.medico');
Route::post('atendimento/{id}/search/paciente', 'PacienteController@search')->name('search.paciente');

//pesquisa do relatorio
Route::post('relatorio/search/periodo', 'RelatorioController@search')->name('search.relatorio');

samel/app/Atendimento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Atendimento extends Model
{
    protected $table = 'atendimentos';

    protected $fillable = [
        'medico_id', 'paciente_id', 'dia'
    ];
}

samel/app/Http/Controllers/AtendimentoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Atendimento;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class AtendimentoController extends Controller
{   
    
    private $atendimento;

    public function __construct(Atendimento $atendimento){
        $this->middleware('auth');
        $this->atendimento = $atendimento;
        
    }
    //view que mostra atendimento por id
    public function show($id){
        try {        

            $data = DB::table('atendimentos') 
                        ->join('medicos', 'medicos.id', '=', 'atendimentos.medico_id')
                        ->join('pacientes', 'pacientes.id', '=', 'atendimentos.paciente_id')
                        ->where('atendimentos.id', '=', $id)
                        ->select('atendimentos.*', 'medicos.nome as medico', 'pacientes.nome as paciente', 'pacientes.plano')
                        ->orderBy('atendimentos.id', 'DESC')->get(); 

            $atendimento = $data[0];

            if(!$data || count($data) == 0 || empty($data) || $data == []){               
                return redirect('atendimento/')->with('error', 'Atendimento não encontrado');  
            }
            
            return view('atendimento.view', compact('atendimento'));
        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('atendimento/')->with('error', $e->getMessage()); 
            }
            return redirect('atendimento/')->with('error', 'Existe um erro na operação'); 
        }        
    }
    
    //view de edicao
    public function edit($id){

        try {           
            $data = DB::table('atendimentos') 
                        ->join('medicos', 'medicos.id', '=', 'atendimentos.medico_id')
                        ->join('pacientes', 'pacientes.id', '=', 'atendimentos.paciente_id')
                        ->where('atendimentos.id', '=', $id)
                        ->select('atendimentos.*', 
                                'medicos.nome as medico', 'medicos.especialidade', 'medicos.crm',
                                'pacientes.nome as paciente', 'pacientes.plano', 'pacientes.telefone')
                        ->get(); 

            $atendimento = $data[0];
            //tratando data ehora para serem editados em inputs diferentes
            $dataAtendimento = explode(" ", $atendimento->dia);
            $atendimento->dia = $dataAtendimento[0];

            //tratando hora que possue apenas minuto e segundo no input
            $horaAtendimento = explode(":", $dataAtendimento[1]);
            $atendimento->hora = $horaAtendimento[0].":".$horaAtendimento[1];


            if(!$data || count($data) == 0 || empty($data) || $data == []){               
                return redirect('atendimento/'.$id.'/edit')->with('error', 'Atendimento não encontrado');  
            }

            return view('atendimento.edit', compact('atendimento'));

        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('atendimento/'.$id.'/edit')->with('error', $e->getMessage()); 
            }
            return redirect('atendimento/'.$id.'/edit')->with('error', 'Existe um erro na operação'); 
        }        
    }
    //exclui registro
    public function destroy($id){

        try {
            $atendimento = $this->atendimento->findOrFail($id); 
            $atendimento->delete(); 
            
            return redirect('atendimento/')->with('success', 'Atendimento excluído com sucesso'); 

        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('atendimento/')->with('error', $e->getMessage()); 
            }
            return redirect('atendimento/')->with('error', 'Existe um erro na operação'); 
        }   
    }
    //view de listagem de todos
    public function index(){

        $atendimentos = DB::table('atendimentos') 
                        ->join('medicos', 'medicos.id', '=', 'atendimentos.medico_id')
                        ->join('pacientes', 'pacientes.id', '=', 'atendimentos.paciente_id')
                        ->whereNull('atendimentos.deleted_at')
                        ->select('atendimentos.*', 'medicos.nome as medico', 'pacientes.nome as paciente', 'pacientes.plano')
                        ->orderBy('atendimentos.id', 'DESC')->paginate(30); 

      
        return view('atendimento.index', compact('atendimentos'));
               
    }
    //view de cadastro
    public function create(){
        return view('atendimento.create');
    }
    //cadastra
    public function store(Request $request){ 

            //usa isso para validar os campos com os valores inseridos
            $this->validate($request, ['medico_id'=>'required|string', 
                                       'paciente_id'=>'required|string',
                                       'dia' => 'required|string',
                                       'hora' => 'required|string']);
            try {
            $data = $request->all();  
            $data['dia'] = $data['dia']." ".$data['hora'].":00";            

            $atendimento = $this->atendimento->create($data);

            return redirect('atendimento/')->with('success', 'Atendimento criado com sucesso'); 
            
        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('atendimento/')->with('error', $e->getMessage()); 
            }
            return redirect('atendimento/')->with('error', 'Existe um erro na operação'); 
        }         
    }
    //edita 
    public function update(Request $request, $id){        
       
        $this->validate($request, ['medico_id'=>'required|string', 
                                    'paciente_id'=>'required|string',
                                    'dia' => 'required|string',
                                    'hora' => 'required|string']);
        try {
            $data = $request->all();  
            $data['dia'] = $data['dia']." ".$data['hora'].":00";  
            $atendimento = $this->atendimento->findOrFail($id);
            $atendimento->update($data);

            return redirect('atendimento/'.$id.'/edit')->with('success', 'Atendimento editado com sucesso');                     

        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('atendimento/'.$id.'/edit')->with('error', $e->getMessage()); 
            }
            return redirect('atendimento/'.$id.'/edit')->with('error', 'Existe um erro na operação'); 
        }          
    }
    
    //desativa o registro apenas usando o campo deleted_at, nao exclui do banco 
    //(verificar se existe esse campo no banco)
    public function delete(Request $request, $id){

        $data = $request->all();
        try {      

            $affected = DB::table('atendimentos')
              ->where('id', $id)
              ->update(['deleted_at' => $data['deleted_at']]);
            
            return redirect('atendimento/')->with('success', "Atendimento desativado com sucesso");                      

        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('atendimento/')->with('error', $e->getMessage()); 
            }
            return redirect('atendimento/')->with('error', 'Existe um erro na operação'); 
        }          
    }

}

samel/resources/views/atendimento/create.blade.php
@extends('layouts.principal')

@section('content')
        <div class="d-sm-flex align-items-center justify-content-between ">
            <h1 class="h3 mb-0 text-gray-800">Adicionar Atendimento</h1>          
        </div>
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-2">
                    <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6"> 
                            <div class="p-3">
                                
                                <!--Nome FORM-->
                                <div class="form-group">
                                    <p class="text-left text-primary p-0">{{ __('Paciente:') }}</p>
                                    <div class="input-group">
                                        <input type="text" name="search_paciente" id="search_paciente" class="form-control small" placeholder="Procurar paciente" aria-label="Search" aria-describedby="basic-addon2">
                                        <input type="hidden" name="_token" id="token-paciente" value="{{ csrf_token() }}">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" onclick="pesquisarPaciente()">
                                            <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>                                        
                                </div>
                                <!--END Nome FORM-->
                                <!--RESULTADO DA PESQUISA DO PACIENTE-->
                                <div id="table-paciente">
                                
                                </div>
                                <!--FIM RESULTADO DA PESQUISA DO PACIENTE-->

                                <!--RESULTADO ESCOLHIDO DA PESQUISA DO PACIENTE-->
                                <div id="paciente-selecionado">
                                
                                </div>   
                                <div id="paciente-escolhido">
                                </div>                             
                                <!--FIM RESULTADO ESCOLHIDO DA PESQUISA DO PACIENTE-->
                                
                                <!--Médico FORM-->    
                                <div class="form-group">
                                    <p class="text-left text-primary p-0">{{ __('Médico:') }}</p>
                                    <div class="input-group">
                                        <input type="text" name="search_medico" id="search_medico" class="form-control small" placeholder="Procurar médico" aria-label="Search" aria-describedby="basic-addon2">
                                        <input type="hidden" name="_token" id="token-medico" value="{{ csrf_token() }}">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" onclick="pesquisarMedico()">
                                            <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>                                        
                                </div>
                                <!--END Médico FORM--> 

                                <!--RESULTADO DA PESQUISA DO Médico-->
                                <div id="table-medico">
                                
                                </div>
                                <!--FIM RESULTADO DA PESQUISA DO Médico-->

                                <!--RESULTADO ESCOLHIDO DA PESQUISA DO Médico-->
                                <div id="medico-selecionado">
                                
                                </div>    
                                <div id="medico-escolhido">    
                                </div>                        
                                <!--FIM RESULTADO ESCOLHIDO DA PESQUISA DO Médico-->

                                <!------------------------FORM DO ATENDIMENTO--------------------------->
                                @include('utils.message')
                                <form class="user" method="POST" action="{{ route('atendimento.store') }}">  
                                    @csrf
                                    <!--Dia FORM-->                            
                                    <div class="form-group">
                                        

                                        @error('paciente_id')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror

                                        <div class="form-row">
                                            <div class="col">
                                                <p class="text-left text-primary p-0">{{ __('Dia:') }}</p>
                                                <input type="date" name="dia" class="form-control @error('dia') is-invalid @enderror" id="dia" aria-describedby="diaHelp" value="{{ old('dia') }}"  autocomplete="dia" autofocus>
                                                @error('dia')
                                                    <span class="invalid-feedback" role="alert">
                                                    <strong>Por favor, informe uma Data</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                            <div class="col">
                                                <p class="text-left text-primary p-0">{{ __('Hora:') }}</p>
                                                <input type="time" name="hora" class="form-control @error('hora') is-invalid @enderror" id="hora" aria-describedby="horaHelp" value="{{ old('hora') }}"  autocomplete="hora" autofocus>
                                                @error('hora')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>Por favor, informe uma Hora</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                        
                                    </div>
                                    <!--END Dia FORM-->    
                                    <input type="hidden" class="form-control @error('medico_id') is-invalid @enderror" name="medico_id" value="{{ old('medico_id') }}" id="medico_id">
                                    @error('medico_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>Por favor, selecione um Médico</strong>
                                        </span>
                                    @enderror
                                    <input type="hidden" class="form-control @error('paciente_id') is-invalid @enderror" name="paciente_id" value="{{ old('paciente_id') }}" id="paciente_id"> 
                                    @error('paciente_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>Por favor, selecione um Paciente</strong>
                                        </span>
                                    @enderror                          
                                   
                                    <div class="form-group row">
                                        <div class="col-md-4 mb-1 offset-md-2">
                                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                                Salvar
                                            </button>
                                        </div>    
                                        <div class="col-md-4">
                                            <a  class="btn btn-primary btn-user btn-block" style="color: #fff;" href="{{ route('atendimento.index') }}">
                                                Cancelar
                                            </a>
                                        </div>                         
                                    </div>  
                                </form>
                                <!------------------------END FORM DO ATENDIMENTO--------------------------->   
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>

    @push('js-funcoes')
        <script src="{{ asset('js/atendimento.js') }}"></script>
    @endpush

@endsection

samel/resources/views/atendimento/edit.blade.php
@extends('layouts.principal')

@section('content')
        <div class="d-sm-flex align-items-center justify-content-between ">
            <h1 class="h3 mb-0 text-gray-800">Editar Atendimento</h1>
            <!--a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a-->
        </div>
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-9">
                <a href="{{route('atendimento.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-1">
                    <i class="fas fa-arrow-left"></i> Voltar</a><br>
                <div class="card o-hidden border-0 shadow-lg my-2">
                    <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6"> 
                            <div class="p-3">
                                <!--Nome FORM-->
                                <div class="form-group">
                                    <p class="text-left text-primary p-0">{{ __('Paciente:') }}</p>
                                    <div class="input-group">
                                        <input type="text" name="search_paciente" id="search_paciente" class="form-control small" placeholder="Procurar paciente" aria-label="Search" aria-describedby="basic-addon2">
                                        <input type="hidden" name="_token" id="token-paciente" value="{{ csrf_token() }}">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" onclick="pesquisarPaciente()">
                                            <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>                                        
                                </div>
                                <!--END Nome FORM-->
                                <!--RESULTADO DA PESQUISA DO PACIENTE-->
                                <div id="table-paciente">
                                
                                </div>
                                <!--FIM RESULTADO DA PESQUISA DO PACIENTE-->

                                <!--RESULTADO ESCOLHIDO DA PESQUISA DO PACIENTE-->
                                <div id="paciente-selecionado">
                                
                                </div>  
                                @if(isset($atendimento))
                                    <div id="paciente-escolhido">
                                        <div class="card mb-3"> 
                                        <div class="card-body">
                                            <div class="row">
                                                <div class="col-lg-6"> 
                                                    <div class="p-3">                            
                                                        <p><b>Nome:</b> {{$atendimento->paciente}}</p>
                                                        <p><b>Telefone:</b> {{$atendimento->telefone}}</p>
                                                        <p><b>Plano de Saúde:</b> {{$atendimento->plano}}</p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div><br>
                                    </div>
                                @endif                        
                                <!--FIM RESULTADO ESCOLHIDO DA PESQUISA DO PACIENTE-->
                                
                                <!--Médico FORM-->    
                                <div class="form-group">
                                    <p class="text-left text-primary p-0">{{ __('Médico:') }}</p>
                                    <div class="input-group">
                                        <input type="text" name="search_medico" id="search_medico" class="form-control small" placeholder="Procurar médico" aria-label="Search" aria-describedby="basic-addon2">
                                        <input type="hidden" name="_token" id="token-medico" value="{{ csrf_token() }}">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button" onclick="pesquisarMedico()">
                                            <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>                                        
                                </div>
                                <!--END Médico FORM--> 

                                <!--RESULTADO DA PESQUISA DO Médico-->
                                <div id="table-medico">
                                
                                </div>
                                <!--FIM RESULTADO DA PESQUISA DO Médico-->

                                <!--RESULTADO ESCOLHIDO DA PESQUISA DO Médico-->
                                <div id="medico-selecionado">
                                
                                </div>    
                                @if(isset($atendimento))
                                    <div id="medico-escolhido">
                                        <div class="card mb-3"> 
                                            <div class="card-body">
                                                <div class="row">
                                                    <div class="col-lg-6"> 
                                                        <div class="p-3">                            
                                                            <p><b>Nome:</b> {{$atendimento->medico}}</p>
                                                            <p><b>Especialidade:</b> {{$atendimento->especialidade}}</p>
                                                            <p><b>CRM:</b> {{$atendimento->crm}}</p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div><br> 
                                    </div>    
                                @endif                      
                                <!--FIM RESULTADO ESCOLHIDO DA PESQUISA DO Médico-->

                                @include('utils.message')
                                <form class="user" method="POST" action="{{ route('atendimento.update', $atendimento->id) }}">  
                                    @csrf
                                    @method("PUT")
                                    <!--Dia FORM-->                            
                                    <div class="form-group">                                        

                                        @error('paciente_id')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror

                                        <div class="form-row">
                                            <div class="col">
                                                <p class="text-left text-primary p-0">{{ __('Dia:') }}</p>
                                                <input type="date" name="dia" class="form-control @error('dia') is-invalid @enderror" id="dia" aria-describedby="diaHelp" value="{{$atendimento->dia}}"  autocomplete="dia" autofocus>
                                                @error('dia')
                                                    <span class="invalid-feedback" role="alert">
                                                    <strong>Por favor, informe uma Data</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                            <div class="col">
                                                <p class="text-left text-primary p-0">{{ __('Hora:') }}</p>
                                                <input type="time" name="hora" class="form-control @error('hora') is-invalid @enderror" id="hora" aria-describedby="horaHelp"  value="{{$atendimento->hora}}"  autocomplete="hora" autofocus>
                                                @error('hora')
                                                    <span class="invalid-feedback" role="alert">
                                                        <strong>Por favor, informe uma Hora</strong>
                                                    </span>
                                                @enderror
                                            </div>
                                        </div>
                                        
                                    </div>
                                    <!--END Dia FORM-->    
                                    <input type="hidden" class="form-control @error('medico_id') is-invalid @enderror" name="medico_id"  value="{{$atendimento->medico_id}}" id="medico_id">
                                    @error('medico_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>Por favor, selecione um Médico</strong>
                                        </span>
                                    @enderror
                                    <input type="hidden" class="form-control @error('paciente_id') is-invalid @enderror" name="paciente_id" value="{{$atendimento->paciente_id}}" id="paciente_id"> 
                                    @error('paciente_id')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>Por favor, selecione um Paciente</strong>
                                        </span>
                                    @enderror                          
                                   
                                    <div class="form-group row">
                                        <div class="col-md-4 mb-1 offset-md-2">
                                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                                Salvar
                                            </button>
                                        </div>    
                                        <div class="col-md-4">
                                            <a  class="btn btn-primary btn-user btn-block" style="color: #fff;" href="{{ route('atendimento.index') }}">
                                                Cancelar
                                            </a>
                                        </div>                         
                                    </div>  
                                </form>                                  
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>
    @push('js-funcoes')
    <script src="{{ asset('js/atendimento.js') }}"></script>
    @endpush

@endsection