samel/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('medico', 'MedicoController');
Route::resource('paciente', 'PacienteController');
Route::resource('atendimento', 'AtendimentoController');
Route::resource('relatorio', 'RelatorioController');

//pesquisas na tela de atendimento
Route::post('atendimento/search/medico', 'MedicoController@search')->name('search.medico');
Route::post('atendimento/search/paciente', 'PacienteController@search')->name('search.paciente');

Route::post('atendimento/{id}/search/medico', 'MedicoController@search')->name('search.medico');
Route::post('atendimento/{id}/search/paciente', 'PacienteController@search')->name('search.paciente');

//pesquisa do relatorio
Route::post('relatorio/search/periodo', 'RelatorioController@search')->name('search.relatorio');

samel/app/Paciente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Paciente extends Model
{
    protected $table = 'pacientes';

    protected $fillable = [
        'nome', 'telefone','plano'
    ];
}

samel/app/Http/Controllers/PacienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Paciente;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class PacienteController extends Controller
{
   
    
    private $paciente;

    public function __construct(Paciente $paciente){

        $this->paciente = $paciente;
        $this->middleware('auth');
    }
    //view que mostra paciente por id
    public function show($id){
        try {
            $data = DB::table('pacientes') 
                            ->where([['pacientes.id', '=', $id]])
                            ->get();         
            if(!$data || count($data) == 0 || empty($data) || $data == []){               
                return redirect('paciente/')->with('error', 'Paciente não encontrado');  
            }
            $paciente = $data[0];
            
            return view('paciente.view', compact('paciente'));
        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('paciente/')->with('error', $e->getMessage()); 
            }
            return redirect('paciente/')->with('error', 'Existe um erro na operação'); 
        }

        
    }
    //view de edicao
    public function edit($id){

        try {
            $paciente = $this->paciente->findOrFail($id);          
            return view('paciente.edit', compact('paciente'));

        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('paciente/')->with('error', $e->getMessage()); 
            }
            return redirect('paciente/')->with('error', 'Existe um erro na operação'); 
        }        
    }
    //exclui registro
    public function destroy($id){

        try {
            $paciente = $this->paciente->findOrFail($id); 
            $paciente->delete(); 
            
            return redirect('paciente/')->with('success', 'Paciente excluído com sucesso'); 

        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('paciente/')->with('error', $e->getMessage()); 
            }
            return redirect('paciente/')->with('error', 'Existe um erro na operação'); 
        }   
    }
    //view de listagem de todos
    public function index(){
      
            $pacientes = $this->paciente->whereNull('deleted_at')
                                ->orderBy('id', 'DESC')->paginate(30);
            return view('paciente.index', compact('pacientes'));
               
    }
    //view de cadastro
    public function create(){
        return view('paciente.create');
    }
    //cadastra
    public function store(Request $request){ 

            //usa isso para validar os campos com os valores inseridos
            $this->validate($request, ['nome'=>'required|string|max:300|regex:/^[a-zA-Z\s]*$/', 
                                       'telefone'=>'required|string|max:14',
                                       'plano' => 'required |string | max:100']);
            try {
            $data = $request->all();    
            $paciente = $this->paciente->create($data);

            return redirect('paciente/')->with('success', 'Paciente criado com sucesso'); 
            
        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('paciente/')->with('error', $e->getMessage()); 
            }
            return redirect('paciente/')->with('error', 'Existe um erro na operação'); 
        }         
    }
    //edita 
    public function update(Request $request, $id){        
       
        $this->validate($request, ['nome'=>'required|string|max:300|regex:/^[a-zA-Z\s]*$/', 
                                    'telefone'=>'required|string|max:14',
                                    'plano' => 'required |string | max:100']);
        try {
            $data = $request->all();  
            $paciente = $this->paciente->findOrFail($id);
            $paciente->update($data);

            return redirect('paciente/'.$id.'/edit')->with('success', 'Paciente editado com sucesso');                     

        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('paciente/'.$id.'/edit')->with('error', $e->getMessage()); 
            }
            return redirect('paciente/'.$id.'/edit')->with('error', 'Existe um erro na operação'); 
        }          
    }
    
    //desativa o registro apenas usando o campo deleted_at, nao exclui do banco 
    //(verificar se existe esse campo no banco)
    public function delete(Request $request, $id){

        $data = $request->all();
        try {      

            $affected = DB::table('pacientes')
              ->where('id', $id)
              ->update(['deleted_at' => $data['deleted_at']]);
            
            return redirect('paciente/')->with('success', "Paciente desativado com sucesso");                      

        } catch (\Exception $e) {
            if(config('app.debug')){
                return redirect('paciente/')->with('error', $e->getMessage()); 
            }
            return redirect('paciente/')->with('error', 'Existe um erro na operação'); 
        }          
    }

    //view de pesquisa de paciente por nome
    public function search(Request $request){
        try {
            $data = json_decode($request->getContent());
            if($data->search_paciente != ""){
                $pacientes = $this->paciente->where('nome', 'ilike', '%'.$data->search_paciente.'%')
                ->orderBy('id', 'DESC')->paginate(30);

                return response()->json($pacientes);
            }else{
                return response()->json([], 404);
            }           

        } catch (\Exception $e) {
            if(config('app.debug')){
                return response()->json($e->getMessage(), 404);
            }
            return response()->json('Existe um erro na operação', 404);
        }           
    }

}

samel/resources/views/paciente/create.blade.php
@extends('layouts.principal')

@section('content')
        <div class="d-sm-flex align-items-center justify-content-between ">
            <h1 class="h3 mb-0 text-gray-800">Adicionar Paciente</h1>          
        </div>
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-9">
                <div class="card o-hidden border-0 shadow-lg my-2">
                    <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6"> 
                            <div class="p-3">
                                
                                <form class="user" method="post" action="{{ route('paciente.store') }}">  
                                    @csrf
                                    <!--Nome FORM-->
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Nome:') }}</p>
                                        <input type="text" name="nome" class="form-control @error('nome') is-invalid @enderror" value="{{ old('nome') }}" id="nome" aria-describedby="nomeHelp"  autofocus placeholder="Ex: Maria">
                                        @error('nome')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div> 
                                    <!--END Nome FORM-->

                                    <!--Telefone FORM-->                            
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Telefone:') }}</p>
                                        <input type="text" name="telefone" class="form-control @error('telefone') is-invalid @enderror" id="telefone" aria-describedby="telefoneHelp" value="{{ old('telefone') }}"  autocomplete="telefone" autofocus placeholder="Ex: 92 992999999">
                                        @error('telefone')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div>
                                    <!--END Telefone FORM-->

                                    <!--Plano FORM-->  
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Plano de Saúde:') }}</p>
                                        <select class="form-control" name="plano" id="plano">
                                            <option value="PME">PME</option>
                                            <option value="Empresarial">Empresarial</option>
                                        </select>
                                    </div>
                                     <!--Plano FORM-->                                     
                                   
                                    <div class="form-group row">
                                        <div class="col-md-4 mb-1 offset-md-2">
                                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                                Salvar
                                            </button>
                                        </div>    
                                        <div class="col-md-4">
                                            <a  class="btn btn-primary btn-user btn-block" style="color: #fff;" href="{{ route('paciente.index') }}">
                                                Cancelar
                                            </a>
                                        </div>                         
                                    </div>  

                                </form>                                    
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

samel/resources/views/paciente/edit.blade.php
@extends('layouts.principal')

@section('content')
        <div class="d-sm-flex align-items-center justify-content-between ">
            <h1 class="h3 mb-0 text-gray-800">Editar Paciente</h1>
            <!--a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a-->
        </div>
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-9">
                <a href="{{route('paciente.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-1">
                    <i class="fas fa-arrow-left"></i> Voltar</a><br>
                <div class="card o-hidden border-0 shadow-lg my-2">
                    <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6"> 
                            <div class="p-3">

                                @include('utils.message')
                        
                                <form class="user" method="POST" action="{{ route('paciente.update', $paciente->id) }}">  
                                    @csrf
                                    @method("PUT")
                                    <!--nome FORM-->
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Nome:') }}</p>
                                        <input type="text" name="nome" class="form-control @error('nome') is-invalid @enderror" value="{{ $paciente->nome }}" id="nome" aria-describedby="nomeHelp" autofocus placeholder="Ex: Maria">
                                        @error('nome')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div> 
                                    <!--END nome FORM-->  

                                    <!--Telefone FORM-->
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Telefone:') }}</p>
                                        <input type="text" name="telefone" class="form-control @error('telefone') is-invalid @enderror" value="{{ $paciente->telefone }}" id="telefone" aria-describedby="telefoneHelp" autofocus placeholder="Ex: 92 992999999">
                                        @error('telefone')
                                            <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                                        @enderror
                                    </div> 
                                    <!--END Telefone FORM--> 

                                    <!--Plano FORM-->
                                    <div class="form-group">
                                        <p class="text-left text-primary p-0">{{ __('Plano de Saúde:') }}</p>
                                        <select class="form-control" name="plano" id="plano">
                                            <option value="PME" 
                                                @if ($paciente->plano == 'PME')
                                                    selected="selected"
                                                @endif >PME</option>
                                            <option value="Empresarial"
                                                @if ($paciente->plano == 'Empresarial')
                                                    selected="selected"
                                                @endif>Empresarial</option>
                                        </select>
                                    </div>
                                    <!--END Plano FORM-->                                    
                                    
                                    <div class="form-group row">
                                        <div class="col-md-4 mb-1 offset-md-2">
                                            <button type="submit" class="btn btn-primary btn-user btn-block">
                                                Salvar
                                            </button>
                                        </div>    
                                        <div class="col-md-4">
                                            <a  class="btn btn-primary btn-user btn-block" style="color: #fff;" href="{{ route('paciente.index') }}">
                                                Cancelar
                                            </a>
                                        </div>                         
                                    </div>  

                                </form>                                    
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>

@endsection

samel/resources/views/paciente/index.blade.php
@extends('layouts.principal')

@section('content')

    <a href="{{route('paciente.create')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-1">
    <i class="fas fa-plus fa-sm text-white-50"></i> Adicionar Paciente</a><br> 

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Paciente Ativos</h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                @include('utils.message')
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Telefone</th>
                    <th>Plano de Saúde</th>
                    <th>Data de Criação</th>
                    <th>Operações</th>
                </tr>
                </thead>
                <tfoot>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Telefone</th>
                    <th>Plano de Saúde</th>
                    <th>Data de Criação</th>
                    <th>Operações</th>
                </tr>
                </tfoot>
                <tbody> 
                @forelse($pacientes as $value)
                    <tr>
                        <td>{{$value->id}}</td>
                        <td>{{$value->nome}}</td>
                        <td>{{$value->telefone}}</td>
                        <td>{{$value->plano}}</td>
                        <td>{{$value->created_at}}</td>
                        <td>
                            
                            <a class="btn btn-info btn-sm" href="{{route('paciente.show', $value->id)}}" alt="Mostrar paciente" title="Mostrar paciente">
                                <i class="fas fa-eye"></i></a>
                                <a class="btn btn-success btn-sm" href="{{route('paciente.edit', $value->id)}}" alt="Editar paciente" title="Editar paciente">
                                <i class="fas fa-user-edit"></i></a>  
                                              
                                <a class="btn btn-danger btn-sm" href="#" alt="Excluir paciente" title="Excluir paciente" 
                                    data-toggle="modal" data-target="#inactiveModal{{$value->id}}">
                                    <i class="fas fa-lock"></i></a>                                    
                          
                                <!-- Delete Modal-->
                                <div class="modal fade" id="inactiveModal{{$value->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Deseja Excluir Paciente?</h5>
                                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">×</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">Selecione "Excluir" para concluir a operação</div>
                                            <div class="modal-footer">
                                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>                                   
                                                <form action="{{ url('/paciente', ['id' => $value->id]) }}" method="post">
                                                    <input class="btn btn-primary" type="submit" value="Excluir" />
                                                    @method('delete')
                                                    @csrf
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </td>
                    </tr> 
                @empty
                <tr>
                        <td colspan="6">
                            <h2>Dados Não Encontrados</h2>
                        </td>
                </tr> 

                
                @endforelse
                </tbody>
                {{$pacientes->links()}}
            </table>
            </div>
        </div>
    </div>

@endsection

samel/resources/views/paciente/view.blade.php
@extends('layouts.principal')

@section('content')
        <div class="d-sm-flex align-items-center justify-content-between ">
            <h1 class="h3 mb-0 text-gray-800">Visualizar Paciente</h1>
        </div>
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-12 col-lg-12 col-md-9">

            <a href="{{route('paciente.index')}}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm mb-1">
                <i class="fas fa-arrow-left"></i> Voltar</a><br>
                <div class="card o-hidden border-0 shadow-lg my-2">
                    
                    <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <div class="col-lg-6"> 
                            <div class="p-3">                            
                                <p><b>Nome:</b> {{$paciente->nome}}</p>
                                <p><b>Telefone:</b> {{$paciente->telefone}}</p>
                                <p><b>Plano de Saúde:</b> {{$paciente->plano}}</p>
                                <p><b>Data de criação:</b> {{$paciente->created_at}}</p>
                                <p><b>Última atualização:</b> {{$paciente->updated_at}}</p>
                            </div>
                        </div>
                    </div>
                    </div>
                </div>
            </div>
        </div>

@endsection